#!/usr/bin/env python3
"""
ReadUp 問題ビルダー
既存の words/questions.js と grammar/questions.js から ReadUp 用 questions.js を生成する。

使い方:
  python3 reading/build_questions.py --count 50    # 50問（初回）
  python3 reading/build_questions.py --count 1000  # 1000問
  python3 reading/build_questions.py --count 5000  # 5000問（全件）
"""
import json, random, argparse, subprocess
from pathlib import Path

BASE = Path(__file__).parent.parent

def load_js_data(js_path):
    """Node.js で questions.js の DATA 配列をパースして返す。"""
    # const → var に変換してevalスコープ問題を回避
    script = (
        f"var src = require('fs').readFileSync({json.dumps(str(js_path))},'utf8');"
        f"src = src.replace(/^const\\s+DATA/m, 'var DATA');"
        f"eval(src);"
        f"process.stdout.write(JSON.stringify(DATA));"
    )
    result = subprocess.run(
        ['node', '-e', script],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"Node.js parse error: {result.stderr}")
    return json.loads(result.stdout)


def load_words(limit=None):
    """WordsUp questions.js から vocab 問題を読み込む。"""
    items = load_js_data(BASE / 'words' / 'questions.js')
    results = []
    for i, q in enumerate(items):
        if limit and len(results) >= limit:
            break
        if not all(k in q for k in ['diff', 'axis', 'word', 'text', 'ja', 'answer', 'choices', 'expl']):
            continue
        # 4択に揃える
        choices = q['choices'][:4]
        if q['answer'] not in choices:
            continue
        results.append({
            'id':      f'rw{i+1:05d}',
            'type':    'vocab',
            'diff':    q['diff'],
            'axis':    q['axis'],
            'word':    q['word'],
            'text':    q['text'],
            'ja':      q['ja'],
            'answer':  q['answer'],
            'choices': choices,
            'expl':    q['expl'],
        })
    return results


def load_grammar(limit=None):
    """GrammarUp questions.js から grammar 問題を読み込む。"""
    items = load_js_data(BASE / 'grammar' / 'questions.js')
    results = []
    for i, q in enumerate(items):
        if limit and len(results) >= limit:
            break
        if not all(k in q for k in ['diff', 'axis', 'stem', 'ja', 'answer', 'choices', 'expl']):
            continue
        # stem → text
        text = q['stem']
        choices = q['choices'][:4]
        if q['answer'] not in choices:
            choices = [q['answer']] + [c for c in q['choices'] if c != q['answer']][:3]
        results.append({
            'id':      f'rg{i+1:05d}',
            'type':    'grammar',
            'diff':    q['diff'],
            'axis':    'grammar',
            'text':    text,
            'ja':      q['ja'],
            'answer':  q['answer'],
            'choices': choices,
            'expl':    q['expl'],
        })
    return results


def write_questions_js(questions, out_path):
    """questions.js に書き出す。"""
    lines = [
        f'// ReadUp questions.js — {len(questions)}問',
        '// Auto-generated by build_questions.py',
        '// type: "vocab" | "grammar"',
        'const DATA = [',
        '',
    ]
    for q in questions:
        word_part = f'  word:{json.dumps(q["word"], ensure_ascii=False)},' if q.get('word') else ''
        choices_json = json.dumps(q['choices'], ensure_ascii=False)
        lines.append(f'  {{ id:{json.dumps(q["id"])}, type:{json.dumps(q["type"])}, diff:{json.dumps(q["diff"])}, axis:{json.dumps(q["axis"])},')
        if word_part:
            lines.append(f'    {word_part}')
        lines.append(f'    text:{json.dumps(q["text"], ensure_ascii=False)},')
        lines.append(f'    ja:{json.dumps(q["ja"], ensure_ascii=False)},')
        lines.append(f'    answer:{json.dumps(q["answer"], ensure_ascii=False)},')
        lines.append(f'    choices:{choices_json},')
        lines.append(f'    expl:{json.dumps(q["expl"], ensure_ascii=False)} }},')
        lines.append('')
    lines.append('];')
    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f"✅ {out_path} に {len(questions)} 問書き出し完了")


def main():
    parser = argparse.ArgumentParser(description='ReadUp questions.js ビルダー')
    parser.add_argument('--count', type=int, default=50, help='出力問題数（デフォルト: 50）')
    parser.add_argument('--vocab-ratio', type=float, default=0.65, help='語彙問題の比率（デフォルト: 0.65）')
    args = parser.parse_args()

    total  = args.count
    n_vocab   = int(total * args.vocab_ratio)
    n_grammar = total - n_vocab

    print(f"📖 ReadUp 問題生成: 語彙 {n_vocab}問 + 文法 {n_grammar}問 = 計 {total}問")

    words   = load_words()
    grammar = load_grammar()
    print(f"  WordsUp: {len(words)}問 利用可能")
    print(f"  GrammarUp: {len(grammar)}問 利用可能")

    # サンプリング（難易度バランスを維持）
    LEVELS = ['lv1','lv2','lv3','lv4','lv5']
    LEVEL_RATIO = [0.25, 0.30, 0.25, 0.15, 0.05]

    def sample_by_level(pool, n):
        by_level = {lv: [q for q in pool if q['diff']==lv] for lv in LEVELS}
        result = []
        for lv, ratio in zip(LEVELS, LEVEL_RATIO):
            target = max(1, round(n * ratio))
            items  = by_level[lv]
            random.shuffle(items)
            result.extend(items[:target])
        # 不足分を残りから補う
        result_set = {q['id'] for q in result}
        remaining  = [q for q in pool if q['id'] not in result_set]
        random.shuffle(remaining)
        while len(result) < n and remaining:
            result.append(remaining.pop())
        return result[:n]

    sampled_vocab   = sample_by_level(words, n_vocab)
    sampled_grammar = sample_by_level(grammar, n_grammar)

    # 難易度順に並べてマージ
    all_q = sampled_vocab + sampled_grammar
    level_order = {lv: i for i, lv in enumerate(LEVELS)}
    all_q.sort(key=lambda q: level_order.get(q['diff'], 99))

    out = BASE / 'reading' / 'questions.js'
    write_questions_js(all_q, out)

    # 難易度分布サマリー
    print("\n📊 難易度分布:")
    for lv in LEVELS:
        n = sum(1 for q in all_q if q['diff']==lv)
        print(f"  {lv}: {n}問")
    print("\n📊 タイプ分布:")
    for t in ['vocab','grammar']:
        n = sum(1 for q in all_q if q['type']==t)
        print(f"  {t}: {n}問")


if __name__ == '__main__':
    main()
