// ReadUp questions.js — v1.0 (50問)
// type: "vocab" | "grammar"
// axis: meaning / phrase / context / idiom / nuance / grammar
const DATA = [

  // ── lv1 語彙 ──────────────────────────────────────────────────
  { id:"r001", type:"vocab", diff:"lv1", axis:"meaning", word:"grateful",
    text:"I'm really grateful for your help with the project.",
    ja:"プロジェクトを手伝ってくれて本当に感謝しています。",
    answer:"感謝している",
    choices:["感謝している","怒っている","退屈している","疲れている"],
    expl:"grateful は「感謝している」という意味。thankful とほぼ同義で、for のあとに感謝の対象がくる。" },

  { id:"r002", type:"vocab", diff:"lv1", axis:"meaning", word:"obvious",
    text:"The answer was so obvious that everyone got it right.",
    ja:"答えがあまりにも明白だったので全員正解だった。",
    answer:"明らかな",
    choices:["明らかな","難しい","曖昧な","面白い"],
    expl:"obvious は「明らかな、見ればわかる」という意味。clearly visible or understood。" },

  { id:"r003", type:"vocab", diff:"lv1", axis:"meaning", word:"hesitate",
    text:"Don't hesitate to ask if you need anything.",
    ja:"何か必要なことがあれば遠慮なく聞いてください。",
    answer:"ためらう",
    choices:["ためらう","急ぐ","忘れる","拒否する"],
    expl:"hesitate は「ためらう、躊躇する」。Don't hesitate to 〜 で「遠慮なく〜してください」。" },

  { id:"r004", type:"vocab", diff:"lv1", axis:"meaning", word:"curious",
    text:"She's always been curious about how things work.",
    ja:"彼女は物事の仕組みにいつも好奇心旺盛だった。",
    answer:"好奇心のある",
    choices:["好奇心のある","怠惰な","慎重な","無関心な"],
    expl:"curious は「好奇心のある、知りたがりの」。curious about 〜 で「〜に興味がある」。" },

  { id:"r005", type:"vocab", diff:"lv1", axis:"meaning", word:"eager",
    text:"The students were eager to learn about the new science project.",
    ja:"生徒たちはその新しい科学プロジェクトについて学ぶことを熱望していた。",
    answer:"熱心に望んでいる",
    choices:["熱心に望んでいる","不安に感じている","満足して安心している","のんびり構えている"],
    expl:"eager は「〜したくてたまらない、熱望している」。be eager to do で「ぜひ〜したい」。" },

  { id:"r006", type:"vocab", diff:"lv1", axis:"phrase", word:"look forward to",
    text:"I'm looking forward to the trip next week.",
    ja:"来週の旅行を楽しみにしています。",
    answer:"〜を楽しみにする",
    choices:["〜を楽しみにする","〜を恐れる","〜を延期する","〜を思い出す"],
    expl:"look forward to 〜 は「〜を楽しみにする」。to のあとは名詞か動名詞（-ing）がくる。" },

  { id:"r007", type:"vocab", diff:"lv1", axis:"phrase", word:"figure out",
    text:"I need to figure out how to fix this.",
    ja:"これをどう直すか考えないといけない。",
    answer:"〜を理解する・解明する",
    choices:["〜を理解する・解明する","〜を壊す","〜を隠す","〜を無視する"],
    expl:"figure out は「理解する、解明する」という意味の句動詞。問題の解決策を考え出す場面でよく使う。" },

  { id:"r008", type:"vocab", diff:"lv1", axis:"context", word:"rough",
    text:"She's had a rough day at work.",
    ja:"仕事でつらい一日だった。",
    answer:"つらい・大変な",
    choices:["つらい・大変な","素晴らしい","普通の","短い"],
    expl:"rough は「ざらざらした」が基本だが、ここでは「つらい、大変な」という比喩的な意味で使われている。" },

  { id:"r009", type:"vocab", diff:"lv1", axis:"phrase", word:"keep up with",
    text:"It's hard to keep up with all the latest news these days.",
    ja:"最近は最新ニュースすべてに追いつき続けるのが難しい。",
    answer:"遅れずについていく",
    choices:["遅れずについていく","すっかり忘れてしまう","積極的に広める","じっくり調べ直す"],
    expl:"keep up with は「〜に遅れず追いつく、〜についていく」。情報・流行・ペースなどについて広く使われる。" },

  { id:"r010", type:"vocab", diff:"lv1", axis:"idiom", word:"let the cat out of the bag",
    text:"He accidentally let the cat out of the bag about the surprise party.",
    ja:"彼は誤ってサプライズパーティーの秘密を漏らしてしまった。",
    answer:"秘密をうっかり漏らす",
    choices:["秘密をうっかり漏らす","場の空気を読み違える","予想外の問題を起こす","責任を他人に押し付ける"],
    expl:"let the cat out of the bag は「うっかり秘密をばらしてしまう」というイディオム。意図せず情報を漏らす状況で使う。" },

  // ── lv1 文法 ──────────────────────────────────────────────────
  { id:"r011", type:"grammar", diff:"lv1", axis:"grammar",
    text:"She ___ a student at this school.",
    ja:"彼女はこの学校の生徒です。",
    answer:"is",
    choices:["is","am","are","be"],
    expl:"主語が She（三人称単数）なので be 動詞は is。I → am、you/we/they → are。" },

  { id:"r012", type:"grammar", diff:"lv1", axis:"grammar",
    text:"They ___ soccer every Sunday.",
    ja:"彼らは毎週日曜にサッカーをする。",
    answer:"play",
    choices:["play","plays","playing","played"],
    expl:"主語が They（複数）なので三単現の s は不要。every Sunday は現在の習慣。" },

  { id:"r013", type:"grammar", diff:"lv1", axis:"grammar",
    text:"I ___ breakfast this morning.",
    ja:"今朝、朝食を食べた。",
    answer:"had",
    choices:["had","have","has","am having"],
    expl:"this morning は過去の時点を指すので過去形 had。have の過去形は had。" },

  { id:"r014", type:"grammar", diff:"lv1", axis:"grammar",
    text:"We ___ to the park tomorrow.",
    ja:"明日、公園に行く予定です。",
    answer:"will go",
    choices:["will go","went","go","going"],
    expl:"tomorrow は未来の時点。will + 動詞の原形で未来を表す。" },

  { id:"r015", type:"grammar", diff:"lv1", axis:"grammar",
    text:"Please look ___ this word in the dictionary.",
    ja:"この単語を辞書で調べてください。",
    answer:"up",
    choices:["up","at","for","on"],
    expl:"look up = 調べる。look at = 見る、look for = 探す。前置詞の使い分けに注意。" },

  // ── lv2 語彙 ──────────────────────────────────────────────────
  { id:"r016", type:"vocab", diff:"lv2", axis:"meaning", word:"reluctant",
    text:"He was reluctant to share his opinion in the meeting.",
    ja:"彼は会議で自分の意見を言うのをためらっていた。",
    answer:"気が進まない",
    choices:["気が進まない","熱心な","確信のある","怒った"],
    expl:"reluctant は「気が進まない、渋っている」。reluctant to 〜 で「〜したがらない」。" },

  { id:"r017", type:"vocab", diff:"lv2", axis:"meaning", word:"subtle",
    text:"There's a subtle difference between the two colors.",
    ja:"その2色には微妙な違いがある。",
    answer:"微妙な・わずかな",
    choices:["微妙な・わずかな","大きな","はっきりした","人工的な"],
    expl:"subtle は「微妙な、かすかな」。目に見えにくい差異を表す。発音注意：b は発音しない（/sʌtl/）。" },

  { id:"r018", type:"vocab", diff:"lv2", axis:"meaning", word:"inevitable",
    text:"Change is inevitable in any growing company.",
    ja:"成長する企業では変化は避けられない。",
    answer:"避けられない",
    choices:["避けられない","望ましい","予想外の","徐々に起こる"],
    expl:"inevitable は「避けられない、必然的な」。It is inevitable that 〜 の形でもよく使う。" },

  { id:"r019", type:"vocab", diff:"lv2", axis:"phrase", word:"come across",
    text:"I came across an old photo while cleaning my room.",
    ja:"部屋を掃除していたら古い写真を見つけた。",
    answer:"偶然見つける",
    choices:["偶然見つける","なくす","探し回る","撮影する"],
    expl:"come across は「偶然出くわす、たまたま見つける」。意図せず見つけるニュアンスがポイント。" },

  { id:"r020", type:"vocab", diff:"lv2", axis:"phrase", word:"put off",
    text:"Stop putting off your homework and just do it.",
    ja:"宿題を先延ばしにするのはやめてやりなさい。",
    answer:"延期する・先延ばしにする",
    choices:["延期する・先延ばしにする","始める","楽しむ","完了する"],
    expl:"put off は「延期する、先延ばしにする」。procrastinate とほぼ同義。put off + 名詞/動名詞。" },

  { id:"r021", type:"vocab", diff:"lv2", axis:"idiom", word:"break the ice",
    text:"He told a joke to break the ice at the party.",
    ja:"彼はパーティーで場を和ませるためにジョークを言った。",
    answer:"場の緊張をほぐす",
    choices:["場の緊張をほぐす","パーティーを台無しにする","退場する","飲み物を用意する"],
    expl:"break the ice は「場の緊張をほぐす、口火を切る」というイディオム。初対面の緊張を解く場面でよく使う。" },

  { id:"r022", type:"vocab", diff:"lv2", axis:"idiom", word:"under the weather",
    text:"I'm feeling a bit under the weather today.",
    ja:"今日はちょっと体調が悪い。",
    answer:"体調が悪い",
    choices:["体調が悪い","機嫌が悪い","天気が気になる","憂鬱だ"],
    expl:"under the weather は「体調が悪い」というイディオム。軽い体調不良に使う。天気とは直接関係ない。" },

  { id:"r023", type:"vocab", diff:"lv2", axis:"context", word:"address",
    text:"We need to address this issue before the deadline.",
    ja:"期限前にこの問題に取り組む必要がある。",
    answer:"（問題に）取り組む・対処する",
    choices:["（問題に）取り組む・対処する","住所を書く","演説する","配達する"],
    expl:"address は名詞「住所」が有名だが、動詞で「（問題に）取り組む、対処する」という意味もある。ビジネスでよく使う。" },

  { id:"r024", type:"vocab", diff:"lv2", axis:"meaning", word:"vague",
    text:"His answer was so vague that nobody in the room knew what he actually meant.",
    ja:"彼の答えはあいまいすぎて、部屋の誰も彼が実際に何を言いたいのかわからなかった。",
    answer:"はっきりしない・曖昧な",
    choices:["はっきりしない・曖昧な","非常に具体的な","遠回しで丁寧な","感情的な"],
    expl:"vague は「漠然とした、はっきりしない」。ambiguous（多義的）とは異なり、単純に不明瞭であることを指す。" },

  { id:"r025", type:"vocab", diff:"lv2", axis:"idiom", word:"pull someone's leg",
    text:"Don't worry — he was just pulling your leg when he said the meeting was cancelled.",
    ja:"心配しないで。会議が中止になったと言ったのは、ただからかっただけだよ。",
    answer:"冗談でからかう",
    choices:["冗談でからかう","無理に引き留めようとする","他人の評判を傷つける","強引に賛成させようとする"],
    expl:"pull someone's leg は「（人を）冗談でからかう」というイディオム。悪意のないユーモアの文脈で使われることが多い。" },

  // ── lv2 文法 ──────────────────────────────────────────────────
  { id:"r026", type:"grammar", diff:"lv2", axis:"grammar",
    text:"She ___ in Tokyo since 2020.",
    ja:"彼女は2020年から東京に住んでいる。",
    answer:"has lived",
    choices:["has lived","lived","lives","is living"],
    expl:"since 2020 は現在完了の継続用法のシグナル。主語が She なので has lived。" },

  { id:"r027", type:"grammar", diff:"lv2", axis:"grammar",
    text:"This cake was ___ by my mother.",
    ja:"このケーキは母が作ったものです。",
    answer:"made",
    choices:["made","make","making","to make"],
    expl:"was + 過去分詞で受動態。make → made（不規則変化）。" },

  { id:"r028", type:"grammar", diff:"lv2", axis:"grammar",
    text:"I'm looking forward ___ seeing you again.",
    ja:"またお会いできるのを楽しみにしています。",
    answer:"to",
    choices:["to","for","at","of"],
    expl:"look forward to + 動名詞（-ing）。to は前置詞なので後ろは名詞/動名詞。" },

  { id:"r029", type:"grammar", diff:"lv2", axis:"grammar",
    text:"If it ___ tomorrow, we will stay home.",
    ja:"明日雨が降ったら、家にいます。",
    answer:"rains",
    choices:["rains","will rain","rained","is raining"],
    expl:"時・条件を表す副詞節（if節）の中では will を使わず現在形。主語 it + 三単現 → rains。" },

  { id:"r030", type:"grammar", diff:"lv2", axis:"grammar",
    text:"He made me ___ the report again.",
    ja:"彼は私にレポートを書き直させた。",
    answer:"write",
    choices:["write","to write","writing","wrote"],
    expl:"使役動詞 make + O + 原形不定詞。to は不要なのが特徴。" },

  // ── lv3 語彙 ──────────────────────────────────────────────────
  { id:"r031", type:"vocab", diff:"lv3", axis:"meaning", word:"resilient",
    text:"Children are remarkably resilient and adapt quickly to change.",
    ja:"子どもは驚くほど回復力があり、変化にすぐ順応する。",
    answer:"回復力のある・立ち直りが早い",
    choices:["回復力のある・立ち直りが早い","傷つきやすい","頑固な","のんびりした"],
    expl:"resilient は「回復力のある、打たれ強い」。困難から立ち直る力を表す。名詞形は resilience。" },

  { id:"r032", type:"vocab", diff:"lv3", axis:"meaning", word:"elaborate",
    text:"Could you elaborate on that point? I didn't quite understand.",
    ja:"その点をもう少し詳しく説明してもらえますか？よく理解できませんでした。",
    answer:"詳しく述べる",
    choices:["詳しく述べる","要約する","反論する","同意する"],
    expl:"elaborate は動詞で「詳しく述べる」、形容詞で「精巧な、手の込んだ」。elaborate on 〜 で「〜について詳しく説明する」。" },

  { id:"r033", type:"vocab", diff:"lv3", axis:"meaning", word:"viable",
    text:"Solar energy is becoming a more viable option for homeowners.",
    ja:"太陽光エネルギーは住宅所有者にとってより現実的な選択肢になりつつある。",
    answer:"実行可能な・現実的な",
    choices:["実行可能な・現実的な","安価な","危険な","複雑な"],
    expl:"viable は「実行可能な、成り立つ」。a viable option/alternative などの形でよく使う。" },

  { id:"r034", type:"vocab", diff:"lv3", axis:"phrase", word:"get away with",
    text:"He can't get away with breaking the rules every time.",
    ja:"彼は毎回ルール違反をして罰を逃れるわけにはいかない。",
    answer:"（罰を受けずに）逃れる",
    choices:["（罰を受けずに）逃れる","ルールを守る","逮捕される","謝罪する"],
    expl:"get away with 〜 は「〜をしても罰を受けずに済む、見逃してもらう」。悪いことをしても咎められないニュアンス。" },

  { id:"r035", type:"vocab", diff:"lv3", axis:"phrase", word:"turn down",
    text:"She turned down the job offer because the salary was too low.",
    ja:"給料が低すぎたので、彼女はその求人を断った。",
    answer:"断る・拒否する",
    choices:["断る・拒否する","受け入れる","検討する","交渉する"],
    expl:"turn down は「断る、拒否する」。decline とほぼ同義。音量を下げるという意味もあるが、文脈で判断。" },

  { id:"r036", type:"vocab", diff:"lv3", axis:"idiom", word:"on the same page",
    text:"Let's make sure we're all on the same page before we start.",
    ja:"始める前に全員が同じ認識でいることを確認しよう。",
    answer:"同じ認識を持っている",
    choices:["同じ認識を持っている","同じ本を読んでいる","同じ場所にいる","意見に反対している"],
    expl:"on the same page は「同じ認識を持っている、共通理解がある」。ビジネスミーティングでよく使われるイディオム。" },

  { id:"r037", type:"vocab", diff:"lv3", axis:"context", word:"sharp",
    text:"Be there at 9 o'clock sharp.",
    ja:"9時きっかりにそこにいて。",
    answer:"きっかり・ちょうど",
    choices:["きっかり・ちょうど","鋭い","賢い","厳しい"],
    expl:"sharp は「鋭い」が基本だが、時間の後ろにつくと「きっかり、ちょうど」の意味。at 3 sharp = 3時ちょうど。" },

  { id:"r038", type:"vocab", diff:"lv3", axis:"nuance", word:"affect",
    text:"The new policy will affect thousands of employees.",
    ja:"新しい方針は何千人もの社員に影響する。",
    answer:"〜に影響を与える（動詞）",
    choices:["〜に影響を与える（動詞）","〜の結果をもたらす（名詞）","〜を実施する","〜を無効にする"],
    expl:"affect は動詞「影響を与える」、effect は名詞「効果、影響」。affect = 動詞、effect = 名詞と覚えるのが基本。" },

  // ── lv3 文法 ──────────────────────────────────────────────────
  { id:"r039", type:"grammar", diff:"lv3", axis:"grammar",
    text:"He speaks English ___ than his brother.",
    ja:"彼は兄よりも上手に英語を話す。",
    answer:"better",
    choices:["better","good","best","well"],
    expl:"well（上手に）の比較級は better。more good は不可。than があるので比較級が必要。" },

  { id:"r040", type:"grammar", diff:"lv3", axis:"grammar",
    text:"The man ___ is standing over there is my uncle.",
    ja:"あそこに立っている男性は私の叔父です。",
    answer:"who",
    choices:["who","which","what","where"],
    expl:"先行詞が The man（人）で主格の関係代名詞 → who。which はものに使う。" },

  // ── lv4 語彙 ──────────────────────────────────────────────────
  { id:"r041", type:"vocab", diff:"lv4", axis:"meaning", word:"ambiguous",
    text:"The contract language is deliberately ambiguous.",
    ja:"契約書の文言は意図的に曖昧にされている。",
    answer:"曖昧な・多義的な",
    choices:["曖昧な・多義的な","明確な","違法な","長い"],
    expl:"ambiguous は「曖昧な、複数の解釈ができる」。vague（漠然とした）と似ているが、ambiguous は「2つ以上の意味に取れる」ニュアンス。" },

  { id:"r042", type:"vocab", diff:"lv4", axis:"meaning", word:"paramount",
    text:"Safety is of paramount importance in this industry.",
    ja:"この業界では安全が最も重要だ。",
    answer:"最も重要な・至上の",
    choices:["最も重要な・至上の","部分的な","最小限の","標準的な"],
    expl:"paramount は「最も重要な、至上の」。of paramount importance で「最重要」。フォーマルな文脈で使う。" },

  { id:"r043", type:"vocab", diff:"lv4", axis:"phrase", word:"boil down to",
    text:"The argument boils down to a matter of trust.",
    ja:"議論は結局のところ信頼の問題に帰着する。",
    answer:"結局〜に帰着する",
    choices:["結局〜に帰着する","沸騰する","議論が激化する","問題が解決する"],
    expl:"boil down to 〜 は「結局〜に帰着する、要約すると〜になる」。複雑な問題の本質を述べる場面で使う。" },

  { id:"r044", type:"vocab", diff:"lv4", axis:"context", word:"critical",
    text:"The report was critical of the government's response to the crisis.",
    ja:"その報告書は危機に対する政府の対応に批判的だった。",
    answer:"批判的な",
    choices:["批判的な","重要な","危機的な","分析的な"],
    expl:"critical は「重要な」「危機的な」という意味が有名だが、ここでは「批判的な」。critical of 〜 で「〜に対して批判的」。" },

  { id:"r045", type:"vocab", diff:"lv4", axis:"context", word:"sound",
    text:"That sounds like a sound plan to me.",
    ja:"それは堅実な計画に思える。",
    answer:"堅実な・確かな（形容詞）",
    choices:["堅実な・確かな（形容詞）","音に関する","大きな","複雑な"],
    expl:"sound は名詞「音」、動詞「〜に聞こえる」の他に、形容詞で「堅実な、確かな」という意味がある。sound advice（確かなアドバイス）。" },

  { id:"r046", type:"vocab", diff:"lv4", axis:"idiom", word:"burn bridges",
    text:"Don't burn bridges with your old company — you might need their reference.",
    ja:"前の会社との関係を断ち切るな——推薦状が必要になるかもしれない。",
    answer:"関係を断ち切る・退路を断つ",
    choices:["関係を断ち切る・退路を断つ","新しい関係を築く","妥協する","競争する"],
    expl:"burn bridges は「関係を断ち切る、退路を断つ」。橋を燃やして戻れなくするイメージ。主に否定形で「関係を壊すな」と使う。" },

  // ── lv5 語彙 ──────────────────────────────────────────────────
  { id:"r047", type:"vocab", diff:"lv5", axis:"meaning", word:"exacerbate",
    text:"The drought exacerbated the already dire food shortage.",
    ja:"干ばつがすでに深刻な食糧不足をさらに悪化させた。",
    answer:"悪化させる",
    choices:["悪化させる","改善する","引き起こす","予防する"],
    expl:"exacerbate は「（すでに悪い状況を）さらに悪化させる」。worsen/aggravate と同義だが、よりフォーマル。" },

  { id:"r048", type:"vocab", diff:"lv5", axis:"meaning", word:"ubiquitous",
    text:"Smartphones have become ubiquitous in modern life.",
    ja:"スマートフォンは現代生活でどこにでもある存在になった。",
    answer:"至る所にある",
    choices:["至る所にある","高価な","必要不可欠な","時代遅れの"],
    expl:"ubiquitous は「至る所にある、遍在する」。everywhere と同義だがフォーマルで書き言葉向き。" },

  { id:"r049", type:"vocab", diff:"lv5", axis:"idiom", word:"cut corners",
    text:"We can't cut corners on safety — lives are at stake.",
    ja:"安全面で手を抜くことはできない——人命がかかっている。",
    answer:"手を抜く・手間を省く",
    choices:["手を抜く・手間を省く","経費を削減する","近道をする","安全策を講じる"],
    expl:"cut corners は「手を抜く、近道をして品質を犠牲にする」。角（corner）をカットして最短距離を行くイメージ。" },

  { id:"r050", type:"vocab", diff:"lv5", axis:"context", word:"appreciate",
    text:"Stock prices are expected to appreciate over the next decade.",
    ja:"株価は今後10年間で値上がりすると予想されている。",
    answer:"価値が上がる",
    choices:["価値が上がる","感謝する","理解する","安定する"],
    expl:"appreciate は「感謝する」が最も一般的だが、金融では「（資産が）価値を上げる」。反意語は depreciate（価値が下がる）。" },

];
